### ISSUE TITLE
Active & accepting PRs for Hacktoberfest 2021?

### ISSUE THREAD

**Issue by AdityaKane2001** [30-seconds/30-seconds-of-python#465]
@kriadmin  @Chalarangelo 

This is a great consolidated repo and I'd like to do some genuine contribution to it during hacktoberfest 2021. Is it open to accept
and review PRs?

**Comment by Chalarangelo** [comment]
Hi there! 👋 

Due to the large amounts of spam in previous iterations of Hacktoberfest, the **30 seconds of code organization will not be officially participating in the event this year**. This means we will not be adding the `hacktoberfest` label to any of our repositories, nor will we encourage new contributors to submit PRs over the next month. 

Valid, high-quality **contributions during that time will be processed as usual**, based on maintainers' availability instead of rushing through them to accommodate the event. If a new contributor wants their PRs to count for Hacktoberfest, they should **tag either me or @Trinityyi in the PR description and specifically state they would like it reviewed as part of the event**, so we can add the `hacktoberfest-accepted` label when we review it. [Standard contribution guidelines](https://github.com/30-seconds/30-seconds-of-python/blob/master/CONTRIBUTING.md) also apply, so make sure you follow them correctly. Bear in mind that if the volume of PRs is too high, we might not be able to get around to reviewing them all, so following these guidelines will help us prioritize them as best we can. 

Lastly, please understand that the organization not participating in event is by no means a discouragement to contribute new content. It is, however, a way to **discourage spam and unnecessary overhead** for both maintainers and contributors that would in turn harm our community. Last year we had to deal with too many problematic contributions and we even had to put repositories on cooldown to deal with the amount of spam and low-quality content we received. We feel that this is not representative of who we are and that our resources are best spent on people who actually want to contribute something meaningful. Shall they want to participate in Hacktoberfest as well, we will of course reward their contribution.

Regards,
The 30 seconds of code team

**Comment by AdityaKane2001** [comment]
@Chalarangelo 

Thanks for the clarification.
