### ISSUE TITLE
[FEATURE] Topic wise Snippets 

### ISSUE THREAD

**Issue by Tikam02** [30-seconds/30-seconds-of-python#93]
### Topic-wise snippets like:
- For web [Flask and Django Snippets]
- For Machine Learning and Data Science [ Numpy, Pandas,etc.]
- For OOPs 

I am experienced in machine learning and Django, can I PR the Topic Feature in the code with some snippets.

**Comment by Chalarangelo** [comment]
If I had more time, I would research this a bit. As it stands, I would rely on community contributions for these categories if we are to implement them. Glad to merge any snippet PRs with this kind of content, though.

**Comment by Tikam02** [comment]
@Chalarangelo I will PR the features I had mentioned above ASAP.
But the installation guide or the details to run the project on the local system were not provided. If you provide some details or commands it will be a great help.

**Comment by fejes713** [comment]
Hey @Tikam02 👋 

Sorry for the delay. In order to run the project locally, you would need to fork it, clone it, and then do the following:

1. `npm install` - to install all dependencies of this project.
2. `npm run webber:dev` will start a development server for you (with hot-reload)

if you happen to change snippets or want to change `README.md` then you have 2 more following commands:

- `npm run extractor` that extracts all code from snippets into a JSON file
- `npm run builder` will build the `README.md` based on extracted JSON file

_note:_ In order for webber:dev to sync with new snippets, you would need to run the `npm extractor` as well if you make changes to them. 

Hope that helps, and let me know if there's something in the process that doesn't work or sounds confusing.

**Comment by Chalarangelo** [comment]
I am closing this one due to inactivity. If anyone has a PR ready for any of the mentioned snippets, I'd gladly take a look.
